CHANGELOG.md
README.md
bin/metrics.dart
lib/src/cli/arguments_parser.dart
lib/src/models/violation_level.dart
lib/src/reporters/utility_selector.dart
test/utility_selector_test.dart

18 exit codes

---

CHANGELOG.md
lib/metrics_analyzer.dart
lib/src/metrics_analysis_recorder.dart
lib/src/metrics_analyzer.dart
lib/src/metrics_records_builder.dart
lib/src/metrics_records_store.dart
test/metrics_analysis_recorder_test.dart

Safe metrics analyzer recorder

---

.github/workflows/build.yml
CHANGELOG.md
README.md
doc/rules/prefer_intl_name.md
lib/src/rules/prefer_intl_name.dart
lib/src/rules_factory.dart
lib/src/utils/iterable_extensions.dart
lib/src/utils/object_extensions.dart
pubspec.yaml
test/rules/prefer_intl_name_test.dart

add rule prefer-intl-name

---

CHANGELOG.md
README.md
doc/rules/prefer_conditional_expressions.md
lib/src/rules/prefer_conditional_expressions.dart
lib/src/rules_factory.dart
test/rules/prefer_conditional_expressions_test.dart

@dkrutskikh can u please take a look?
Closes #41

Prefer conditional expressions rule implementation

---

CHANGELOG.md
README.md
doc/rules/no_object_declaration.md
lib/src/rules/no_object_declaration.dart
lib/src/rules_factory.dart
test/rules/no_object_declaration_test.dart

@dkrutskikh can u please take a look?
Closes #38

No object declaration rule implementation

---

lib/src/rules/prefer_conditional_expressions.dart
test/rules/prefer_conditional_expressions_test.dart

Conditional expressions correction

---

README.md
doc/rules/member_ordering.md
lib/src/rules/member_ordering.dart
lib/src/rules_factory.dart
test/rules/member_ordering_test.dart

@dkrutskikh can u please take a look?
Also, are there any rules for change log update?
closes #37

Members ordering rule implementation

---

doc/rules/no_magic_number.md
lib/src/rules/no_magic_number_rule.dart
test/rules/no_magic_number_rule_test.dart

Improve no magic number

---

CHANGELOG.md
README.md

[x] Documentation update
[ ] Bug fix
[ ] New rule
Updates tool description and readme formatting.

Update tool description

---

analysis_options.yaml
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/lines_of_code/function_body_ast_visitor.dart
lib/src/models/code_issue.dart
lib/src/reporters/console_reporter.dart
lib/src/reporters/json_reporter.dart
lib/src/rules/avoid_preserve_whitespace_false.dart
lib/src/rules/base_rule.dart
lib/src/rules/binary_expression_operand_order_rule.dart
lib/src/rules/double_literal_format_rule.dart
lib/src/rules/member_ordering.dart
lib/src/rules/newline_before_return.dart
lib/src/rules/no_boolean_literal_compare_rule.dart
lib/src/rules/no_empty_block.dart
lib/src/rules/no_magic_number_rule.dart
lib/src/rules/no_object_declaration.dart
lib/src/rules/prefer_conditional_expressions.dart
lib/src/rules/prefer_intl_name.dart
lib/src/rules/prefer_on_push_cd_strategy.dart
lib/src/rules/prefer_trailing_comma_for_collection.dart
lib/src/rules/rule_utils.dart
test/metrics_analysis_recorder_test.dart
test/reporters/code_climate_reporter_test.dart
test/reporters/console_reporter_test.dart
test/reporters/json_reporter_test.dart

[ ] Bug fix
[ ] New rule
[x] Add something to the core
Add static diagnostic documentation url
none

Add rule documentation url

---

lib/src/analyzer_plugin/analyzer_plugin.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain:

Tiny cleanup code

---

lib/src/rules/member_ordering.dart

[x] Bug fix
[ ] New rule
Fixed type cast of YamlList.

Fix member-ordering rule configuration

---

lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/models/code_issue_severity.dart
lib/src/reporters/code_climate/code_climate_issue.dart
lib/src/reporters/console_reporter.dart

[ ] Bug fix
[ ] New rule
[X] Add something to the core
Add new severity type Error to existing Style & Warning

add Error code issue severity

---

analysis_options.yaml
bin/metrics.dart
lib/src/ignore_info.dart
lib/src/rules/prefer_intl_name.dart
test/rules/member_ordering_test.dart
test/rules/no_magic_number_rule_test.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: activate some linter rules and fix found issues

activate some linter rules

---

analysis_options.yaml
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/cli/arguments_parser.dart
lib/src/cli/arguments_validation.dart
lib/src/ignore_info.dart
lib/src/reporters/console_reporter.dart
test/metrics_analysis_runner_test.dart
tool/format_coverage.dart

Stabialize plugin

---

bin/metrics.dart
lib/src/analysis_options.dart
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/metrics_analyzer.dart
lib/src/utils/yaml_utils.dart
lib/src/utils/yaml_utls.dart
test/analysis_options_test.dart
test/resources/analysis_options_common.yaml
test/resources/analysis_options_main.yaml
test/resources/analysis_options_with_metrics.yaml

[x] Bug fix
[ ] New rule
Closie #68

Improve excludes

---

lib/src/analyzer_plugin/analyzer_plugin.dart

[x] Bug fix
[ ] New rule
Closes the issue when we show in suggestions all available for the file fixes. This fix limits suggestions to selected line.

Fix suggested fixes count

---

README.md
doc/rules/binary_expression_operand_order.md
doc/rules/double_literal_format.md
doc/rules/member_ordering.md
doc/rules/no_boolean_literal_compare.md
doc/rules/no_magic_number.md
doc/rules/prefer_conditional_expressions.md
doc/rules/prefer_intl_name.md
doc/rules/prefer_trailing_comma_for_collection.md

[x] Documentation update
[ ] Bug fix
[ ] New rule

Add labels to rule descriptions

---

lib/src/analyzer_plugin/analyzer_plugin.dart

Added able to ignore metrics warning

---

CHANGELOG.md
README.md
doc/rules/component_annotation_arguments_ordering.md
lib/src/rules/component_annotation_arguments_ordering.dart
lib/src/rules_factory.dart
test/rules/component_annotation_arguments_ordering_test.dart

[ ] Bug fix
[x] New rule
Closes #92

Component annotation arguments ordering rule implementation

---

lib/src/analysis_options.dart
test/analysis_options_test.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: deprecate obsolete code

Deprecation

---

bin/metrics.dart
lib/src/analysis_options.dart
lib/src/cli/arguments_parser.dart
test/analysis_options_test.dart

[X] Bug fix
[ ] New rule
Fix metrics levels read order (cli args, analysis_options, default settings)

Metrics levels

---

lib/src/lines_of_code/lines_with_code_ast_visitor.dart
lib/src/metrics_analyzer.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: internal refactoring

Lines with code ast visitor

---

README.md
bin/metrics.dart
doc/metrics/lines-of-executable-code.md
example/example.dart
lib/src/analysis_options.dart
lib/src/cli/arguments_parser.dart
lib/src/models/config.dart
lib/src/models/file_report.dart
lib/src/models/function_report.dart
lib/src/reporters/code_climate/code_climate_issue.dart
lib/src/reporters/code_climate/code_climate_reporter.dart
lib/src/reporters/console_reporter.dart
lib/src/reporters/html_reporter.dart
lib/src/reporters/json_reporter.dart
lib/src/reporters/utility_selector.dart
test/analysis_options_test.dart
test/reporters/code_climate_reporter_test.dart
test/reporters/console_reporter_test.dart
test/reporters/json_reporter_test.dart
test/reporters/utility_selector_test.dart
test/resources/analysis_options_repo.yaml
test/stubs_builders.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: fix issue #99

Lines of code

---

README.md
doc/anti-patterns/long-method.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/anti_patterns/base_pattern.dart
lib/src/anti_patterns/long_method.dart
lib/src/anti_patterns_factory.dart
lib/src/metrics_analysis_recorder.dart
lib/src/metrics_analyzer.dart
lib/src/metrics_records_builder.dart
lib/src/models/design_issue.dart
lib/src/models/file_record.dart
lib/src/reporters/code_climate/code_climate_issue.dart
lib/src/reporters/code_climate/code_climate_reporter.dart
lib/src/reporters/console_reporter.dart
lib/src/reporters/json_reporter.dart
test/analyzer_plugin/analyzer_plugin_utils_test.dart
test/anti_patterns/long_method_test.dart
test/anti_patterns_factory_test.dart
test/metrics_analysis_recorder_test.dart
test/metrics_analysis_runner_test.dart
test/reporters/code_climate_reporter_test.dart
test/reporters/console_reporter_test.dart
test/reporters/json_reporter_test.dart
test/reporters/utility_selector_test.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: add anti pattern long-method

Long method

---

analysis_options.yaml
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_config.dart
test/analyzer_plugin/analyzer_plugin_utils_test.dart
test/models/code_issue_severity_test.dart
test/models/violation_level_test.dart

Per driver config

---

README.md
analysis_options.yaml
lib/src/analysis_options.dart
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_config.dart
lib/src/anti_patterns_factory.dart
lib/src/metrics_analyzer.dart
test/analysis_options_test.dart
test/anti_patterns_factory_test.dart

Anti patterns in options

---

lib/src/analysis_options.dart
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/anti_patterns/long_method.dart
lib/src/metrics_analyzer.dart
test/analysis_options_test.dart
test/rules_factory_test.dart

Some fixes

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

Prepare to release

---

CHANGELOG.md
bin/metrics.dart
lib/src/analysis_options.dart
lib/src/cli/arguments_parser.dart
lib/src/models/config.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: remove deprecated code

Cleanup deprecations p1

---

CHANGELOG.md
README.md
analysis_options.yaml
doc/anti-patterns/long-parameter-list.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/anti_patterns/base_pattern.dart
lib/src/anti_patterns/long_method.dart
lib/src/anti_patterns/long_parameter_list.dart
lib/src/anti_patterns/pattern_utils.dart
lib/src/anti_patterns_factory.dart
lib/src/metrics_analyzer.dart
lib/src/models/source.dart
lib/src/reporters/code_climate/code_climate_issue.dart
lib/src/reporters/code_climate/code_climate_reporter.dart
test/anti_patterns/long_method_test.dart
test/anti_patterns/long_parameter_list_test.dart
test/reporters/code_climate_reporter_test.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: add static code anti-patterns long-parameter-list

Long parameter list

---

.github/workflows/build.yml
CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

[ ] Bug fix
[ ] New rule
[x] Other, please explain: Set min SDK version to >=2.8.0

Min sdk 2 8 0

---

CHANGELOG.md
bin/metrics.dart
example/example.dart
lib/metrics_analyzer.dart
lib/src/metrics_analysis_recorder.dart
lib/src/metrics_analysis_runner.dart
lib/src/metrics_analyzer.dart
lib/src/metrics_records_store.dart
test/metrics_analysis_recorder_test.dart
test/metrics_analysis_runner_test.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: remove deprecated code, close #60

Cleanup deprecations p2

---

CHANGELOG.md
bin/metrics.dart
example/example.dart
lib/src/metrics_analysis_runner.dart
lib/src/metrics_analyzer.dart
test/metrics_analysis_runner_test.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: Migrate on resolve from parseString

Migrate on resolve

---

lib/src/reporters/html/html_reporter.dart
lib/src/reporters/html/utility_functions.dart
test/reporters/html/utility_functions_test.dart

Html report show issues

---

CHANGELOG.md
README.md
doc/rules/no_equal_arguments.md
doc/rules/no_equal_then_else.md
lib/src/rules/no_equal_arguments.dart
lib/src/rules_factory.dart
test/rules/no_equal_arguments_test.dart

[ ] Bug fix
[X] New rule
Closes #132

No equal arguments rule implementation

---

analysis_options.yaml
lib/src/rules/member_ordering.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: update linter rules

Dart 2.10.0

---

.github/workflows/build.yml

[ ] Bug fix
[ ] New rule
[X] Other, please explain:

Migrate on unified developer tool

---

CHANGELOG.md
README.md
analysis_options.yaml
doc/rules/component_annotation_arguments_ordering.md
doc/rules/member_ordering.md
doc/rules/prefer_trailing_comma.md
lib/src/rules/prefer_trailing_comma.dart
lib/src/rules_factory.dart
test/rules/prefer_trailing_comma/examples/correct_example.dart
test/rules/prefer_trailing_comma/examples/example.dart
test/rules/prefer_trailing_comma/examples/incorrect_example.dart
test/rules/prefer_trailing_comma/prefer_trailing_comma_test.dart

[ ] Bug fix
[X] New rule
Closes #152

Prefer trailing comma rule implementation

---

lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/anti_patterns/base_pattern.dart
lib/src/anti_patterns/long_method.dart
lib/src/anti_patterns/long_parameter_list.dart
lib/src/metrics_analyzer.dart
test/anti_patterns/long_method_test.dart
test/anti_patterns/long_parameter_list_test.dart
test/cli/arguments_validation_test.dart

Improve anti patterns

---

.github/workflows/build.yml
pubspec.yaml

[ ] Bug fix
[ ] New rule
[x] Other, please explain: new major version of dependency_validator

migrate on new major version of dependency_validator

---

README.md
analysis_options.yaml
bin/metrics.dart
doc/metrics/maximum-nesting.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/config/analysis_options.dart
lib/src/config/cli/arguments_parser.dart
lib/src/config/config.dart
lib/src/metrics/nesting_level/nesting_level_visitor.dart
lib/src/metrics_analyzer.dart
lib/src/models/file_report.dart
lib/src/models/function_record.dart
lib/src/models/function_report.dart
lib/src/reporters/code_climate/code_climate_issue.dart
lib/src/reporters/code_climate/code_climate_reporter.dart
lib/src/reporters/console_reporter.dart
lib/src/reporters/html/html_reporter.dart
lib/src/reporters/html/resources/main.css
lib/src/reporters/html/utility_functions.dart
lib/src/reporters/json_reporter.dart
lib/src/reporters/utility_selector.dart
test/analysis_options_test.dart
test/metrics/nesting_level/examples/example.dart
test/metrics/nesting_level/nesting_level_visitor_test.dart
test/reporters/code_climate_reporter_test.dart
test/reporters/console_reporter_test.dart
test/reporters/html/utility_functions_test.dart
test/reporters/json_reporter_test.dart
test/reporters/utility_selector_test.dart
test/stubs_builders.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: maximum nesting metric

Maximum Nesting

---

doc/anti-patterns/long-method.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/anti_patterns/long_method.dart
lib/src/anti_patterns/long_parameter_list.dart
lib/src/models/function_record.dart
lib/src/models/function_type.dart
lib/src/models/scoped_function_declaration.dart
lib/src/scope_ast_visitor.dart
test/anti_patterns/long_method_test.dart
test/anti_patterns/long_parameter_list_test.dart
test/metrics_analysis_recorder_test.dart
test/scope_ast_visitor_test.dart
test/utils/metrics_analyzer_utils_test.dart

Function type

---

pubspec.yaml

upgrade deps

---

lib/src/reporters/code_climate/code_climate_reporter.dart
test/reporters/code_climate_reporter_test.dart

[X] Bug fix
[ ] New rule
Each issue must be terminated by the null character (\0 in most programming languages), but can additionally be separated by newlines. (https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#output)

Fix codeclimate report

---

CONTRIBUTING.md
analysis_options.yaml
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/reporters/json_reporter.dart
lib/src/rules/rule_utils.dart
pubspec.yaml
test/metrics_analysis_recorder_test.dart
test/reporters/code_climate_reporter_test.dart
test/reporters/console_reporter_test.dart
test/reporters/github_reporter_test.dart
test/reporters/json_reporter_test.dart
test/rules/avoid_preserve_whitespace_false_test.dart
test/rules/binary_expression_operand_order_rule_test.dart
test/rules/double_literal_format_rule_test.dart
test/rules/newline_before_return_test.dart
test/rules/no_boolean_literal_compare_rule_test.dart
test/rules/no_empty_block_test.dart
test/rules/prefer_conditional_expressions_test.dart
test/rules/prefer_intl_name_not_correct_name_test.dart
test/rules/prefer_intl_name_not_exists_name_test.dart
test/rules/prefer_trailing_comma/prefer_trailing_comma_test.dart
test/rules/prefer_trailing_comma_for_collection_test.dart
test/rules/provide_correct_intl_args_not_correct_test.dart

migrate on Replacement

---

CONTRIBUTING.md
lib/src/rules/avoid_preserve_whitespace_false.dart
lib/src/rules/avoid_unused_parameters.dart
lib/src/rules/binary_expression_operand_order_rule.dart
lib/src/rules/component_annotation_arguments_ordering.dart
lib/src/rules/double_literal_format_rule.dart
lib/src/rules/member_ordering.dart
lib/src/rules/newline_before_return.dart
lib/src/rules/no_boolean_literal_compare_rule.dart
lib/src/rules/no_empty_block.dart
lib/src/rules/no_equal_arguments.dart
lib/src/rules/no_equal_then_else.dart
lib/src/rules/no_magic_number_rule.dart
lib/src/rules/no_object_declaration.dart
lib/src/rules/potential_null_dereference.dart
lib/src/rules/prefer_conditional_expressions.dart
lib/src/rules/prefer_intl_name.dart
lib/src/rules/prefer_on_push_cd_strategy.dart
lib/src/rules/prefer_trailing_comma.dart
lib/src/rules/prefer_trailing_comma_for_collection.dart
lib/src/rules/provide_correct_intl_args.dart
pubspec.yaml

Read severity

---

lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/metrics_analyzer.dart
pubspec.yaml
test/anti_patterns/long_method_test.dart
test/anti_patterns/long_parameter_list_test.dart
test/utils/metrics_analyzer_utils_test.dart

Number of methods

---

lib/src/reporters/utility_selector.dart
pubspec.yaml

migrate on valueLevel

---

lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/reporters/code_climate/code_climate_reporter.dart
lib/src/reporters/console_reporter.dart
lib/src/reporters/utility_selector.dart
pubspec.yaml
test/reporters/utility_selector_test.dart

migrate on isReportLevel

---

bin/metrics.dart
doc/metrics/weight-of-class.md
lib/src/config/analysis_options.dart
lib/src/config/cli/arguments_parser.dart
lib/src/config/config.dart
lib/src/metrics_analyzer.dart
lib/src/models/component_record.dart
lib/src/models/component_report.dart
lib/src/reporters/utility_selector.dart
test/stubs_builders.dart

Weight Of Class metric

---

lib/src/rules/provide_correct_intl_args.dart
test/rules/provide_correct_intl_args_correct_test.dart

Change value on lxeme

---

README.md

[ ] Bug fix
[ ] New rule
#closes #195

Add docs about Quick Fixes

---

CHANGELOG.md
README.md
bin/metrics.dart
lib/src/config/cli/arguments_parser.dart
lib/src/reporters/html/html_reporter.dart

close #211 
[ ] Bug fix
[ ] New rule
[x] Add a CLI option

Allow configuring output directory for HTML reporter

---

analysis_options.yaml
bin/metrics.dart
example/example.dart
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/config/analysis_options.dart
lib/src/metrics_analyzer.dart
lib/src/models/function_record.dart
lib/src/reporters/code_climate/code_climate_issue.dart
lib/src/reporters/html/html_reporter.dart
lib/src/reporters/utility_selector.dart
pubspec.yaml
test/analysis_options_test.dart
test/analyzer_plugin/analyzer_plugin_utils_test.dart
test/anti_patterns/long_method_test.dart
test/anti_patterns/long_parameter_list_test.dart
test/metrics_analysis_recorder_test.dart
test/rules/avoid_preserve_whitespace_false_test.dart
test/rules/binary_expression_operand_order_rule_test.dart
test/rules/double_literal_format_rule_test.dart
test/rules/newline_before_return_test.dart
test/rules/no_boolean_literal_compare_rule_test.dart
test/rules/no_empty_block_test.dart
test/rules/no_magic_number_rule_test.dart
test/rules/prefer_intl_name_not_correct_name_test.dart
test/rules/prefer_intl_name_not_exists_name_test.dart
test/rules/prefer_on_push_cd_strategy_test.dart
test/rules/prefer_trailing_comma_for_collection_test.dart
test/rules/provide_correct_intl_args_not_correct_test.dart
test/stubs_builders.dart

Bump code checker

---

README.md
lib/src/metrics_analysis_recorder.dart
lib/src/metrics_analyzer.dart
lib/src/metrics_records_builder.dart
pubspec.yaml
test/metrics_analysis_recorder_test.dart

Switch code_checker to 0.4.2

---

lib/src/metrics_analysis_recorder.dart
lib/src/metrics_analyzer.dart
lib/src/models/file_record.dart
lib/src/models/function_record.dart
lib/src/reporters/utility_selector.dart
pubspec.yaml
test/reporters/code_climate_reporter_test.dart
test/reporters/console_reporter_test.dart
test/reporters/github_reporter_test.dart
test/reporters/json_reporter_test.dart
test/reporters/utility_selector_test.dart
test/stubs_builders.dart

Switch code_checker to 0.4.4

---

lib/src/models/class_type.dart
lib/src/models/function_type.dart
lib/src/models/metric_value_level.dart
lib/src/models/replacement.dart
lib/src/models/severity.dart
lib/src/obsoleted/analyzer_plugin/analyzer_plugin.dart
lib/src/obsoleted/metrics_analyzer.dart
lib/src/suppression.dart
test/resources/suppression_example.dart
test/suppression_test.dart

added suppression

---

lib/src/models/scoped_class_declaration.dart
lib/src/models/scoped_function_declaration.dart
lib/src/scope_visitor.dart
test/resources/abstract_class.dart
test/resources/class_with_factory_constructors.dart
test/resources/extension.dart
test/resources/functions.dart
test/resources/mixin.dart
test/resources/weight_of_class_example.dart
test/scope_visitor_test.dart

added scope visitor

---

lib/src/metrics/class_metric.dart
lib/src/metrics/cyclomatic_complexity/cyclomatic_complexity_flow_visitor.dart
lib/src/metrics/function_metric.dart
lib/src/metrics/maximum_nesting_level/nesting_level_visitor.dart
lib/src/metrics/metric.dart
lib/src/metrics/metric_computation_result.dart
lib/src/models/rule_documentation.dart
lib/src/rules/rule.dart
lib/src/utils/metric_utils.dart
lib/src/utils/node_utils.dart
lib/src/utils/rule_utils.dart
test/metrics/class_metric_test.dart
test/metrics/cyclomatic_complexity/cyclomatic_complexity_flow_visitor_test.dart
test/metrics/function_metric_test.dart
test/metrics/maximum_nesting_level/nesting_level_visitor_test.dart
test/resources/cyclomatic_complexity_metric_example.dart
test/resources/maximum_nesting_level_metric_example.dart
test/utils/metric_utils_test.dart
test/utils/node_utils_test.dart
test/utils/rule_utils_test.dart

add base metrics

---

lib/src/obsoleted/metrics_analysis_recorder.dart
lib/src/obsoleted/metrics_analyzer.dart

Fix empty overridden method call

---

bin/metrics.dart
lib/src/obsoleted/config/analysis_options.dart
lib/src/obsoleted/config/config.dart
lib/src/obsoleted/metrics_analysis_recorder.dart
lib/src/obsoleted/models/file_record.dart
lib/src/obsoleted/reporters/code_climate/code_climate_reporter.dart
lib/src/obsoleted/reporters/console_reporter.dart
lib/src/obsoleted/reporters/json_reporter.dart
lib/src/obsoleted/reporters/utility_selector.dart
test/obsoleted/metrics_analysis_recorder_test.dart
test/obsoleted/metrics_analysis_runner_test.dart
test/obsoleted/reporters/code_climate_reporter_test.dart
test/obsoleted/reporters/console_reporter_test.dart
test/obsoleted/reporters/github_reporter_test.dart
test/obsoleted/reporters/json_reporter_test.dart
test/obsoleted/reporters/utility_selector_test.dart

Remove legacy constants

---

bin/metrics.dart
example/example.dart
lib/src/config/config.dart
lib/src/obsoleted/analyzer_plugin/analyzer_plugin.dart
lib/src/obsoleted/analyzer_plugin/analyzer_plugin_config.dart
lib/src/obsoleted/anti_patterns/base_pattern.dart
lib/src/obsoleted/anti_patterns/long_method.dart
lib/src/obsoleted/anti_patterns/long_parameter_list.dart
lib/src/obsoleted/config/analysis_options.dart
lib/src/obsoleted/metrics_analyzer.dart
test/config/analysis_options_test.dart
test/config/config_test.dart
test/obsoleted/analysis_options_test.dart
test/obsoleted/anti_patterns/long_method_test.dart
test/obsoleted/anti_patterns/long_parameter_list_test.dart
test/obsoleted/resources/analysis_options_pkg.yaml
test/obsoleted/resources/analysis_options_repo.yaml
test/resources/analysis_options_common.yaml
test/resources/analysis_options_pkg.yaml
test/resources/analysis_options_repo.yaml

refactor: migrate from obsoleted AnalysisOptions

---

test/obsoleted/rules/member_ordering_extended/examples/example.dart
test/obsoleted/rules/member_ordering_extended/member_ordering_extened_rule_test.dart

Fix member ordering extended tests

---

lib/src/obsoleted/metrics_analysis_runner.dart
lib/src/obsoleted/metrics_analyzer.dart
test/obsoleted/metrics_analysis_runner_test.dart

[X] Bug fix
[ ] New rule
Fix a strange behaviour with a mocked `MetricsAnalyzer` and update return value.

Fix test with mocktail mock

---

lib/src/obsoleted/analyzer_plugin/analyzer_plugin.dart
tools/analyzer_plugin/pubspec.yaml

fix: read analysis_options in plugin

---

test/metrics/cyclomatic_complexity/cyclomatic_complexity_flow_visitor_test.dart
test/metrics/cyclomatic_complexity/cyclomatic_complexity_metric_test.dart
test/metrics/lines_of_code_metric_test.dart
test/metrics/maximum_nesting_level/maximum_nesting_level_metric_test.dart
test/metrics/maximum_nesting_level/nesting_level_visitor_test.dart
test/metrics/number_of_methods_test.dart
test/metrics/number_of_parameters_metric_test.dart
test/metrics/weight_of_class_test.dart
test/obsoleted/rules/avoid_unused_parameters/avoid_unused_parameters_test.dart
test/obsoleted/rules/member_ordering_extended/member_ordering_extened_rule_test.dart
test/obsoleted/rules/no_object_declaration/no_object_declaration_test.dart
test/obsoleted/rules/prefer_trailing_comma/prefer_trailing_comma_test.dart
test/scope_visitor_test.dart
test/suppression_test.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: a small tests refactoring

Refactor tests example path

---

.vscode/settings.json
CHANGELOG.md
pubspec.yaml

build: update dependency on analyzer_plugin

---

README.md
TROUBLESHOOTING.md

Add troubleshooting docs

---

bin/metrics.dart
example/example.dart
lib/reporters.dart
lib/src/obsoleted/metrics_analyzer.dart
lib/src/obsoleted/reporters/code_climate/code_climate_reporter.dart
lib/src/obsoleted/reporters/console_reporter.dart
lib/src/obsoleted/reporters/github/github_reporter.dart
lib/src/obsoleted/reporters/html/html_reporter.dart
lib/src/obsoleted/reporters/json_reporter.dart
lib/src/obsoleted/reporters/reporter.dart
lib/src/reporter_factory.dart
lib/src/reporters/reporter.dart
test/obsoleted/reporters/code_climate_reporter_test.dart
test/obsoleted/reporters/console_reporter_test.dart
test/obsoleted/reporters/github_reporter_test.dart
test/obsoleted/reporters/json_reporter_test.dart
test/reporter_factory_test.dart

[ ] Bug fix
[ ] New rule
[x] Other, please explain: refactor public api for reporting

Reporter factory

---

lib/src/utils/rule_utils.dart

Close #267 
[X] Bug fix
[ ] New rule

fix: for obsolete rule get documentation url from rule model

---

doc/reporters/github-reporter.md

[ x ] Documentation update
closes https://github.com/dart-code-checker/dart-code-metrics/issues/246
GitHub reporter documentation

Added GitHub reporter steps

---

lib/reporters.dart
lib/src/config/analysis_options.dart
lib/src/obsoleted/rules/no_magic_number_rule.dart
test/metrics/cyclomatic_complexity/cyclomatic_complexity_flow_visitor_test.dart
test/obsoleted/rules/binary_expression_operand_order_rule_test.dart

[X] Bug fix: Close #277 
[ ] New rule

fix: fix problem with cast in no-magic-number

---

CHANGELOG.md
doc/rules/no_boolean_literal_compare.md
lib/src/obsoleted/rules/no_boolean_literal_compare_rule.dart
test/obsoleted/rules/no_boolean_literal_compare/examples/example.dart
test/obsoleted/rules/no_boolean_literal_compare/no_boolean_literal_compare_rule_test.dart

[X] Bug fix
[ ] New rule
Close #266

Improve no-boolean-literal-compare

---

.github/workflows/build.yaml
dart_dependency_validator.yaml
pubspec.yaml

build: migrate on setup-dart action

---

lib/src/analyzer_plugin/plugin_utils.dart
lib/src/obsoleted/analyzer_plugin/analyzer_plugin.dart
lib/src/obsoleted/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/obsoleted/metrics_analyzer.dart
test/analyzer_plugin/plugin_utils_test.dart
test/obsoleted/analyzer_plugin/analyzer_plugin_utils_test.dart

[x] Bug fix: Closing #268 
[ ] New rule

Excludes Windows style files

---

.github/workflows/build.yaml

[ ] Bug fix
[ ] New rule
[x] Other, please explain: setup Flutter environment on ci/cd

build: setup flutter environment on CI/CD

---

CHANGELOG.md
README.md
doc/rules/member_ordering_extended.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/models/file_record.dart
lib/src/rules/intl_base/intl_base_visitor.dart
lib/src/rules/member_ordering_extended/config_parser.dart
lib/src/rules/member_ordering_extended/member_ordering_extended_rule.dart
lib/src/rules/member_ordering_extended/models/annotation.dart
lib/src/rules/member_ordering_extended/models/field_keyword.dart
lib/src/rules/member_ordering_extended/models/member_group.dart
lib/src/rules/member_ordering_extended/models/member_type.dart
lib/src/rules/member_ordering_extended/models/modifier.dart
lib/src/rules_factory.dart
pubspec.yaml
test/rules/member_ordering_extended/examples/alphabetical_example.dart
test/rules/member_ordering_extended/examples/example.dart
test/rules/member_ordering_extended/examples/multiple_classes_example.dart
test/rules/member_ordering_extended/member_ordering_extened_rule_test.dart

Backport member ordering rule

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_test.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/examples/example.dart

[ ] Bug fix
[ ] New rule
[X] Changes an existing rule
Closes #292

Support getters in avoid-returning-widgets rule

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin_utils.dart

[x] Bug fix
[ ] New rule
Backport fix excludes on Windows OS.

fix: excludes on Windows OS

---

CONTRIBUTING.md

[x] Documentation update
[ ] Bug fix
[ ] New rule
I added some contributing instructions about how to run analyzer plugin in IDE from locally cloned git working copy.
I work only on Windows machines and do not have `MacOS/Linux` development experience so new instructions might be `Windows` specific. My English might be not good enough :)

docs: add IDE integration setup instructions in CONTRIBUTING.md

---

.vscode/settings.json
CHANGELOG.md
README.md
lib/src/analyzers/lint_analyzer/metrics_analyzer.dart
pubspec.yaml

[x] Bug fix
[ ] New rule
Close #317

fix: remove unnecessary scan by `lines-of-executable-code`

---

README.md
doc/anti-patterns/long-method.md
doc/metrics/cyclomatic-complexity.md
doc/metrics/lines-of-code.md
doc/metrics/maximum-nesting-level.md
doc/metrics/number-of-methods.md
doc/metrics/number-of-parameters.md
doc/metrics/source-lines-of-code.md
doc/metrics/weight-of-class.md
doc/rules/avoid-returning-widgets.md
doc/rules/member-ordering-extended.md

Doc update

---

example/example.dart
lib/config.dart
lib/metrics_analyzer.dart
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/lint_config.dart
lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_methods_metric.dart
lib/src/analyzers/lint_analyzer/metrics/metrics_list/weight_of_class_metric.dart
lib/src/analyzers/lint_analyzer/metrics/scope_utils.dart
lib/src/analyzers/lint_analyzer/metrics/scope_visitor.dart
lib/src/cli/cli_runner.dart
lib/src/config_builder/config_builder.dart
lib/src/config_builder/models/analysis_options.dart
lib/src/config_builder/models/config.dart
test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method/long_method_test.dart
test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list/long_parameter_list_test.dart
test/analyzers/lint_analyzer/lint_analyzer_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/cyclomatic_complexity/cyclomatic_complexity_flow_visitor_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/cyclomatic_complexity/cyclomatic_complexity_metric_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/lines_of_code_metric_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/maximum_nesting_level/maximum_nesting_level_metric_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/maximum_nesting_level/nesting_level_visitor_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/number_of_methods_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/source_lines_of_code/source_code_visitor_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/source_lines_of_code/source_lines_of_code_metric_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/weight_of_class_test.dart
test/analyzers/lint_analyzer/scope_visitor_test.dart
test/analyzers/utils/scope_utils_test.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: refactor config

refactor: create separate config builder

---

.gitattributes

Partially fixes #329: enforcing LF line endings when checking out the repository.

feat: add .gitattributes to enforce LF line endings

---

.vscode/settings.json

Just noticed https://github.com/dart-code-checker/dart-code-metrics/commit/edbf813f0e8aaadef8cdf0bca1d3bda591de429a, this is an attempt to make final new lines consistent.

chore: enforce final new line in files in Visual Studio Code

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/models/annotation.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/visitor.dart

fix: fix problem with class members classification

---

.github/workflows/build.yaml
test/analyzers/lint_analyzer/lint_analyzer_test.dart
test/utils/exclude_utils_test.dart

[ ] Bug fix
[ ] New rule
[ ] Other, please explain: Close #301

add windows on CI/CD

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/visitor.dart
test/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/examples/alphabetical_correct_example.dart
test/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/member_ordering_extended_test.dart

Fix alphabetize

---

lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart

[X] Bug fix
[ ] New rule
Potentially fix for #289 issue.

Resolve cli

---

.github/workflows/build.yaml

build: rollback subosito flutter action

---

lib/src/analyzers/lint_analyzer/reporters/reporters_list/github/lint_github_reporter.dart
lib/src/reporters/github_workflow_commands.dart
test/reporters/resources/github_workflow_commands_test.dart

fix: GitHubReporter reports issues with invalid file path

---

analysis_options.yaml
test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_test.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate_test.dart
test/analyzers/lint_analyzer/rules/rules_list/member_ordering/member_ordering_test.dart
test/analyzers/lint_analyzer/rules/rules_list/no_equal_then_else/no_equal_then_else_test.dart
test/analyzers/lint_analyzer/rules/rules_list/no_object_declaration/no_object_declaration_test.dart
test/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/prefer_conditional_expressions_test.dart
test/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/prefer_trailing_comma_test.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: disable analysis rule

chore: disable rule and remove ignores

---

lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate_test.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/examples/example.dart

fix: improve setState detection in inline functions

---

lib/src/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/visitor.dart

chore: migrate from `firstWhereOrNull` on `any`

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/visitor.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters_test.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/examples/incorrect_example.dart

[X] Bug fix
[ ] New rule
A fix for #372

feat: make rule compatible with default analyzer rule

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/models/internal_resolved_unit_result.dart
lib/src/utils/node_utils.dart
lib/src/utils/path_utils.dart
test/analyzer_plugin/analyzer_plugin_utils_test.dart
test/analyzers/lint_analyzer/lint_analyzer_test.dart
test/analyzers/unused_files_analyzer/unused_files_analyzer_test.dart
test/helpers/file_resolver.dart
test/utils/exclude_utils_test.dart
test/utils/node_utils_test.dart
test/utils/path_utils_test.dart

[X] Bug fix: Closing #375 
[ ] New rule

Plugin absolute paths

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart

fix: problem with metrics in LSP mode

---

CHANGELOG.md
analysis_options.yaml
lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart
lib/src/cli/commands/check_unused_files.dart
test/analyzers/unused_files_analyzer/unused_files_analyzer_test.dart
test/resources/unused_files_analyzer/generated/intl/messages_all.dart
test/resources/unused_files_analyzer/generated/intl/messages_en.dart
test/resources/unused_files_analyzer/generated/intl/messages_ru.dart
test/resources/unused_files_analyzer/unused_files_example.dart

fix(unused-files): fix unused files analysis for excluded files

---

.gitignore
CHANGELOG.md
README.md
doc/rules/prefer-extracting-callbacks.md
lib/src/analyzers/lint_analyzer/rules/flutter_rule_utils.dart
lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/always_remove_listener.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visit_declaration.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_wrapping_in_padding/avoid_wrapping_in_padding.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_wrapping_in_padding/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/config_parser.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/prefer_extracting_callbacks.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart
test/analyzer_plugin/analyzer_plugin_utils_test.dart
test/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/examples/example.dart
test/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/prefer_extracting_callbacks_test.dart

feat(analyzer): implement prefer extracting callbacks rule

---

analysis_options.yaml
lib/src/analyzers/lint_analyzer/metrics/metrics_list/source_lines_of_code/source_lines_of_code_metric.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/json/lint_json_reporter.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/component_annotation_arguments_ordering/visitor.dart
test/analyzers/lint_analyzer/rules/rules_factory_test.dart
test/stubs_builders.dart

chore: fix avoid-unused-parameters issues

---

lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/config_builder/config_builder.dart
test/analyzers/lint_analyzer/rules/rules_factory_test.dart

[x] Bug fix
[ ] New rule
Skip files whose not analyze by analyzer package.
Like this:
```
./ios/.symlinks/plugins/**
```

fix: skip unanalyzed files

---

doc/anti-patterns/long-method.md
lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart
test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method/examples/widget.dart
test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method/long_method_test.dart

feat: improve long method

---

.github/workflows/build.yaml
example/example.dart
lib/lint_analyzer.dart
lib/reporters.dart
lib/unused_files_analyzer.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: exports update

feat: update exports before release

---

.github/workflows/build.yaml

switch on action

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart

fix: disable metrics highlight for plugin

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/visitor.dart
test/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/always_remove_listener_test.dart
test/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/examples/value_notifier_example.dart

fix: correctly handle generics for always remove listeners rule

---

analysis_options.yaml
pubspec.yaml

[ ] Bug fix
[ ] New rule
[X] Other, please explain: migration from deprecated package

chore: migrate on lints package.

---

pubspec.yaml

chore: add dev dependency on intl package

---

CHANGELOG.md
lib/src/config_builder/analysis_options_utils.dart
test/config_builder/models/analysis_options_test.dart
test/resources/analysis_options_pkg.yaml
test/resources/analysis_options_repo.yaml

[X] Bug fix #398 
[ ] New rule

Fix config overriding

---

.github/workflows/build.yaml
.github/workflows/dartcodemetrics.yaml

chore: extract self check in separate workflow

---

lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart

fix: fix unused files analyzer files extraction

---

README.md

documentation: melos

---

lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: import path update

chore: change import path

---

.github/workflows/lint_pr_title.yaml
CONTRIBUTING.md

[ ] Bug fix
[ ] New rule
[X] Other, please explain: setup new GitHub Action

build: add PR title lint action

---

lib/src/analyzers/lint_analyzer/reporters/reporters_list/console/lint_console_reporter.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/console/lint_console_reporter_helper.dart
lib/src/analyzers/lint_analyzer/reporters/utility_selector.dart
test/analyzers/lint_analyzer/reporters/reporters_list/lint_console_reporter_helper_test.dart
test/analyzers/lint_analyzer/reporters/reporters_list/lint_console_reporter_test.dart
test/analyzers/lint_analyzer/reporters/reporters_list/lint_json_reporter_test.dart
test/analyzers/lint_analyzer/reporters/reporters_list/report_example.dart
test/analyzers/lint_analyzer/reporters/utility_selector_test.dart
test/analyzers/lint_analyzer/rules/rules_factory_test.dart

refactor: update console reporter

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart
pubspec.yaml
test/helpers/file_resolver.dart
tools/analyzer_plugin/pubspec.yaml

[ ] Bug fix
[ ] New rule
[x] Other, please explain:

chore: update analyzer dependency

---

lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/prefer_trailing_comma.dart

fix: change prefer-trailing-comma rule type

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzers/lint_analyzer/lint_analysis_config.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/config_builder/config_builder.dart
lib/src/config_builder/models/analysis_options.dart
test/analyzers/lint_analyzer/lint_config_test.dart
test/config_builder/models/analysis_options_test.dart

fix: fix rule and metric excludes for monorepos

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/visitor.dart
test/analyzers/lint_analyzer/rules/rules_factory_test.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters_test.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/examples/correct_example.dart
test/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/examples/incorrect_example.dart

fix: avoid-unused-parameters now support abstract methods

---

CHANGELOG.md
example/example.dart
lib/src/analyzers/lint_analyzer/lint_analysis_config.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/lint_config.dart
lib/src/config_builder/config_builder.dart
test/analyzers/lint_analyzer/lint_analyzer_test.dart
test/analyzers/lint_analyzer/lint_config_test.dart

feat: add support for global rules-exclude

---

CHANGELOG.md
README.md
lib/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/reporters/utility_selector.dart
lib/src/analyzers/lint_analyzer/utils/report_utils.dart
lib/src/cli/commands/analyze.dart
lib/src/cli/models/flag_names.dart
lib/src/cli/models/parsed_arguments.dart
test/analyzer_plugin/analyzer_plugin_utils_test.dart
test/analyzers/lint_analyzer/reporters/utility_selector_test.dart
test/analyzers/lint_analyzer/utils/report_utils_test.dart
test/cli/commands/analyze_test.dart

[ ] Bug fix
[ ] New rule
[X] Add a CLI option

feat: introduce `--fatal-xxxx` cli arguments

---

.pubignore

[ ] Bug fix
[ ] New rule
[X] Other, please explain: tune publishing on pub

chore: add .pubignore

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/reporters/reporters_list/github/lint_github_reporter.dart
test/analyzers/lint_analyzer/reporters/reporters_list/lint_github_reporter_test.dart

refactor: deprecate GitHub reporter

---

.github/workflows/lint_pr_title.yaml

[ ] Bug fix
[ ] New rule
[X] Other, please explain: setup changelog update check action

ci: add changelog update check action

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/visitor.dart
lib/src/analyzers/unused_files_analyzer/unused_files_visitor.dart
test/resources/unused_files_analyzer/annotation_file.dart
test/resources/unused_files_analyzer/unused_file.dart

[ ] Bug fix
[ ] New rule
[X] Other, please explain: unused files check improvements

feat: add pragma vm:entry-point as entry point for unused files check

---

pubspec.yaml

Add documentation link to the info panel on pub.dev.

chore: add documentation link to the pubspec(and pub.dev)

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/metrics/metrics_factory.dart
lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric.dart
lib/src/config_builder/config_builder.dart
test/analyzers/lint_analyzer/lint_analyzer_test.dart
test/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric_test.dart
test/resources/number_of_parameters_metric_example.dart

fix: compute NumberOfParametersMetric only for functions and methods

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/metrics/metrics_factory.dart
lib/src/analyzers/lint_analyzer/metrics/metrics_list/source_lines_of_code/source_code_visitor.dart
lib/src/config_builder/config_builder.dart

fix: skip synthetic tokens while compute 'Source lines of Code'

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/metrics/metrics_list/maintainability_index_metric.dart
test/analyzers/lint_analyzer/metrics/metrics_list/maintainability_index_metric_test.dart

fix: update 'Maintainability Index' metric comment message

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric.dart
test/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric_test.dart
test/resources/number_of_parameters_metric_example.dart

fix: ‘Number of Parameters’ skip copyWith methods.

---

lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/prefer_const_border_radius.dart
test/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/prefer_const_border_radius_test.dart

[ ] Bug fix
[ ] New rule
[x] Changes an existing rule

feat: update const border radius replacement text

---

.github/workflows/website_check.yaml
.github/workflows/website_deploy.yaml
.pubignore

build: automate website

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/config_parser.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/member_ordering_extended_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/examples/type_alphabetical_example.dart
test/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/member_ordering_extened_rule_test.dart
website/docs/rules/common/member-ordering-extended.md

[ ] Bug fix
[ ] New rule
[X] Changes an existing rule

feat: add alphabetical sorting by type

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/node_utils.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid-unnecessary-type-casts/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_type_assertions/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/prefer_match_file_name_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/examples/multiple_enums.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/examples/multiple_extensions.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/examples/multiple_mixins.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/prefer_match_file_name_rule_test.dart
website/docs/rules/common/prefer-match-file-name.md

…-name` rule.
[ ] Bug fix
[ ] New rule

feat: support mixins, extensions and enums for `prefer-match-file-name`

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin_utils.dart
test/src/analyzer_plugin/analyzer_plugin_utils_test.dart

chore: migrate from deprecated api

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/utils/report_utils.dart
lib/src/cli/commands/check_unused_files_command.dart
lib/src/cli/commands/check_unused_l10n_command.dart
lib/src/cli/models/flag_names.dart
test/src/analyzers/lint_analyzer/lint_analyzer_test.dart
test/src/cli/commands/check_unused_files_command_test.dart
test/src/cli/commands/check_unused_l10n_command_test.dart

fix: returns 0 exit code while found unused files or l10n in cli mode

---

.pubignore
CHANGELOG.md
codecov.yml

[ ] Bug fix
[ ] New rule
[ ] Other, please explain: disable github_checks annotations from codecov (https://docs.codecov.com/docs/codecovyml-reference#github_checks-github-users-only)

chore: disable github_checks annotations from codecov

---

.github/workflows/package_analyze.yaml

chore: tune GitHub workflow

---

CHANGELOG.md
website/docs/rules/common/avoid-throw-in-catch-block.md
website/docs/rules/common/avoid-unnecessary-type-assertions.md
website/docs/rules/common/avoid-unnecessary-type-casts.md
website/docs/rules/common/prefer-correct-identifier-length.md
website/docs/rules/common/prefer-correct-type-name.md

fix: add missing severity

---

website/docs/getting-started/configuration.md

[X ] Documentation update
[ ] Bug fix
[ ] New rule
#https://github.com/dart-code-checker/dart-code-metrics/issues/620
website\docs\getting-started\configuration.md
```yaml title="analysis_options.yaml"
analyzer:
exclude:
- "example/**"
- "build/**"
- "**/*.g.dart"
- "**/*.freezed.dart"
```

docs: updated excludes example with paths for exclude.

---

CONTRIBUTING.md

[ ] Bug fix
[ ] New rule
Added step to CONTRIBUTING.md for Android Studio on macOS users.

docs: Changed CONTRIBUTING.md

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_correct_type_name/validator.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_correct_type_name/examples/class_example.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_correct_type_name/prefer_correct_type_name_rule_test.dart
test/src/helpers/file_resolver.dart
test/src/helpers/rule_test_helper.dart

[x] Bug fix
[ ] New rule
I've added skipping empty type names. This is rare case but I catch them. While you start create new class, after type:
```dart
class 
```
You can face exception:
```
RangeError (index): Invalid value: Valid value range is empty: 0
#0      _StringBase.[] (dart:core-patch/string_patch.dart:260:41)
#1      _Validator.isUpperCase (package:dart_code_metrics/src/analyzers/lint_analyzer/rules/rules_list/prefer_correct_type_name/validator.dart:23:21)
#2      _Validator.isValid (package:dart_code_metrics/src/analyzers/lint_analyzer/rules/rules_list/prefer_correct_type_name/validator.dart:16:8)
#3 …
```

feat: improve `prefer-correct-type-name` rule

---

website/docusaurus.config.js

docs: add link to Flutter Linting Comparsion

---

website/src/css/custom.css

docs: fix footer padding

---

website/docusaurus.config.js

Update website config

---

.github/workflows/package_analyze.yaml
CHANGELOG.md

build: activate check_unused_files on CI

---

CHANGELOG.md
lib/src/analyzers/unused_l10n_analyzer/unused_l10n_visitor.dart
test/resources/unused_l10n_analyzer/test_i18n.dart
test/resources/unused_l10n_analyzer/unused_l10n_analyzer_example.dart
website/docusaurus.config.js

fix: support static getters for check unused l10n

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart
lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart
lib/src/analyzers/lint_analyzer/anti_patterns/models/pattern.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/lint_utils.dart
lib/src/analyzers/lint_analyzer/rules/rule_utils.dart
test/src/analyzers/lint_analyzer/lint_utils_test.dart
test/src/analyzers/lint_analyzer/rules/rule_utils_test.dart
website/docs/getting-started/configuration.md

feat: support excludes for a separate anti-pattern.

---

analysis_options.yaml

chore: avoid-global-state, prefer-correct-type-name rule

---

CHANGELOG.md
analysis_options.yaml
lib/src/analyzers/unused_code_analyzer/models/file_elements_usage.dart
lib/src/analyzers/unused_code_analyzer/models/prefix_element_usage.dart
lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart
lib/src/analyzers/unused_code_analyzer/used_code_visitor.dart
test/resources/unused_code_analyzer/conditional_file.dart
test/resources/unused_code_analyzer/generated/some_file.freezed.dart
test/resources/unused_code_analyzer/not_used.dart
test/resources/unused_code_analyzer/public_members.dart
test/resources/unused_code_analyzer/unconditional_file.dart
test/resources/unused_code_analyzer/unused_code_example.dart
test/src/analyzers/unused_code_analyzer/unused_code_analyzer_test.dart

fix: support excludes and conditional imports for check-unused-code

---

CHANGELOG.md
pubspec.yaml

chore: restrict `analyzer` version to `>=2.4.0 <3.3.0`

---

website/docusaurus.config.js

[ ] Bug fix
[ ] New rule
[X] Other, please explain: update algolia integration

chore: update algolia integration

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/no_magic_number_rule.dart
test/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/examples/example.dart

fix: correcly handle const maps

---

CONTRIBUTING.md

[x] Documentation update
[ ] Bug fix
[ ] New rule

fix: wrong path

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/avoid_border_all_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/examples/example.dart

fix: added parameter constant check in `avoid-border-all`.

---

CHANGELOG.md
pubspec.yaml

chore: set min `mocktail` version to `^0.3.0`

---

CHANGELOG.md

[ ] Bug fix
[ ] New rule
[X] Other, please explain:
Added links to changelog.

chore: added links to documentation in changelog.

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart
lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart
pubspec.yaml

chore: restrict analyzer version

---

.github/workflows/package_analyze.yaml
CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart
lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart
pubspec.yaml

chore: restrict `analyzer` version to `>=3.3.0 <3.4.0`

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/prefer_commenting_analyzer_ignores.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/visitor.dart
test/resources/suppression_example.dart
test/src/analyzers/lint_analyzer/models/suppression_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/examples/example.dart
test/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/prefer_commenting_analyzer_ignores_rule_test.dart
website/docs/rules/common/prefer-commenting-analyzer-ignores.md
website/docs/rules/overview.md

feat: add static code diagnostic prefer-commenting-analyzer-ignores

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/avoid_collection_methods_with_unrelated_types_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/avoid_collection_methods_with_unrelated_types_rule_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/examples/nullable_example.dart

fix: correctly handle nullable types of collections

---

.github/dependabot.yml

chore: tune dependabot

---

CHANGELOG.md
website/docs/rules/common/prefer-async-await.md

docs: update prefer-async-await rule

---

CHANGELOG.md
CONTRIBUTING.md
README.md
lib/src/version.dart
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml
website/docs/getting-started/installation.md

chore: support analyzer 4.0.0

---

.github/workflows/package_analyze.yaml

chore: tune ci/cd

---

CHANGELOG.md
pubspec.yaml

chore: restrict analyzer version to >=2.4.0 <4.2.0

---

.gitlab-ci.yml

[ ] Bug fix
[ ] New rule
[x] Other, please explain:
https://hub.docker.com/r/google/dart/ is discontinued and I adjusted the image accordingly.

Image google/dart is discontinued

---

website/docs/rules/common/avoid-banned-imports.md

chore: update rule title

---

CHANGELOG.md
pubspec.yaml

chore: support analyzer 4.2.0

---

analysis_options.yaml
pubspec.yaml

chore: migrate on lints 2.0.0

---

.github/workflows/package_analyze.yaml
CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_starter.dart
lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/utils/config_parser.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/config_parser.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_single_widget_per_file/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/provide_correct_intl_args/visitor.dart
lib/src/analyzers/unnecessary_nullable_analyzer/reporters/reporter_factory.dart
lib/src/analyzers/unnecessary_nullable_analyzer/unnecessary_nullable_analyzer.dart
lib/src/analyzers/unused_code_analyzer/reporters/reporter_factory.dart
lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart
lib/src/analyzers/unused_files_analyzer/reporters/reporter_factory.dart
lib/src/analyzers/unused_l10n_analyzer/reporters/reporter_factory.dart
lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart
pubspec.yaml
test/src/utils/exclude_utils_test.dart

[ ] Bug fix
[ ] New rule
[X] Add something to the core

feat: migrate to new analyzer plugins API

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/visitor.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_duplicate_exports/avoid_duplicate_exports_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_duplicate_exports/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/avoid_banned_imports_rule_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_duplicate_exports/avoid_duplicate_exports_rule_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_duplicate_exports/examples/example.dart
website/docs/rules/common/avoid-duplicate-exports.md
website/docs/rules/overview.md

feat: add avoid-duplicate-exports rule

---

CHANGELOG.md
lib/src/cli/cli_runner.dart

fix: add zero exit to command runner

---

CHANGELOG.md
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzer_plugin/analyzer_plugin_starter.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/visitor.dart
lib/src/analyzers/unused_code_analyzer/used_code_visitor.dart
lib/src/analyzers/unused_l10n_analyzer/unused_l10n_visitor.dart
pubspec.yaml

chore: revert analyzer-plugin

---

website/docs/cli/overview.md

Add `check-unnecessary-nullable` in [available commands](https://dartcodemetrics.dev/docs/cli/overview#available-commands)

docs: Add check-unnecessary-nullable in available commands

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_rule_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/examples/not_named_parameter_example.dart

fix: support not named builder parameters for avoid-returning-widgets

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters_rule_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/examples/incorrect_example.dart

fix: support variables shadowing for avoid-unused-parameters

---

CHANGELOG.md
lib/src/analyzers/unnecessary_nullable_analyzer/unnecessary_nullable_analyzer.dart
test/resources/unnecessary_nullable_analyzer/nullable_widget_key_parameters.dart
test/resources/unnecessary_nullable_analyzer/unnecessary_nullable_example.dart
test/src/analyzers/unnecessary_nullable_analyzer/unnecessary_nullable_analyzer_test.dart

fix: make check-unnecessary-nullable command ignore Flutter keys

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_top_level_members_in_tests/avoid_top_level_members_in_tests_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_correct_test_file_name/prefer_correct_test_file_name_rule.dart
website/docs/rules/common/avoid-top-level-members-in-tests.mdx
website/docs/rules/common/prefer-correct-test-file-name.mdx

fix: fix excludes for rules intended only for tests

---

CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/config_parser.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/missing_test_assertion_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/examples/correct_example.dart
test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/examples/custom_assertions_example.dart
test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/examples/incorrect_example.dart
test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/missing_test_assertion_test.dart
website/docs/rules/common/missing-test-assertion.mdx

- https://github.com/dart-code-checker/dart-code-metrics/issues/1019
- Visitor file

feat: add static code diagnostic missing-test-assertion

---

.github/workflows/package_analyze.yaml
CHANGELOG.md
lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_cascade_after_if_null/avoid_cascade_after_if_null_rule.dart
lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_cascade_after_if_null/visitor.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_cascade_after_if_null/avoid_cascade_after_if_null_rule_test.dart
test/src/analyzers/lint_analyzer/rules/rules_list/avoid_cascade_after_if_null/examples/example.dart
website/docs/rules/common/avoid-cascade-after-if-null.mdx
website/docs/rules/index.mdx

After https://twitter.com/CptPixel/status/1580596198221545476

feat: add avoid-cascade-after-if-null rule

---

CHANGELOG.md
example/example.dart
lib/src/analyzer_plugin/analyzer_plugin.dart
lib/src/analyzers/lint_analyzer/lint_analysis_config.dart
lib/src/analyzers/lint_analyzer/lint_analysis_options_validator.dart
lib/src/analyzers/lint_analyzer/lint_analyzer.dart
lib/src/analyzers/lint_analyzer/lint_config.dart
lib/src/analyzers/lint_analyzer/models/lint_file_report.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/checkstyle/lint_checkstyle_reporter.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/code_climate/lint_code_climate_reporter.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/console/lint_console_reporter.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/html/lint_html_reporter.dart
lib/src/analyzers/lint_analyzer/reporters/reporters_list/json/lint_json_reporter.dart
lib/src/analyzers/lint_analyzer/reporters/utility_selector.dart
lib/src/analyzers/lint_analyzer/utils/report_utils.dart
lib/src/config_builder/config_builder.dart
lib/src/config_builder/models/analysis_options.dart
test/src/analyzers/lint_analyzer/anti_patterns/patterns_factory_test.dart
test/src/analyzers/lint_analyzer/lint_analyzer_test.dart
test/src/analyzers/lint_analyzer/lint_config_test.dart

feat: add validation for rule names in analysis_options

---

.vscode/extensions.json

chore: setup recommended vscode extensions

---

README.md

Updated links to documentation parts
1. getting started
2. anti patterns
3. additional rules

docs(readme): update links to new docs base url path
