lib/src/analysis_options.dart, test/analysis_options_test.dart
AnalysisOptions missed "number of methods" option reading from configuration.
=> Allow number of methods warning level configuration

lib/src/rules/prefer_conditional_expressions.dart, test/rules/prefer_conditional_expressions_test.dart
[x] Bug fix
[ ] New rule
I have added a check for if statement parent not to be an if statement.
=> Fix false positive trigger for prefer-conditional-expression rule

lib/src/rules/member_ordering.dart, test/rules/member_ordering_test.dart
[x] Bug fix
[ ] New rule
Initial implementation was considering that there will be a new instance of visitor per parsed class, but it turned out that it creates a single instance for parsed file. This fix allows to get rid of false positives in files with multiple classes.
I have change the way the rule processes content. Its now an `accept` method instead of `visitChildren`.
=> Fix member-ordering rule multiple classes processing

CHANGELOG.md, README.md, pubspec.yaml
I explained how to use the tool with Flutter. This was not obvious before for two reasons:
* When using Flutter, the Pub executables directory is not added to path by default.
* The `metrics` executable uses `pub`, which is not available when using Flutter (only `flutter pub` is available).
=> Explain how to use the tool with Flutter

lib/src/ignore_info.dart, test/ignore_info_test.dart
[X] Bug fix
[ ] New rule
Ignore rules in the analyzed code were not being canonicalized during matching, only when constructing the rule cache. This could have led to a potential mis-application of the ignore comments.
closes #183
=> (#183) Rules are not canonicalized during matching

CHANGELOG.md, README.md, doc/rules/avoid_returning_widgets.md, lib/src/rules/avoid_preserve_whitespace_false.dart, lib/src/rules/avoid_returning_widgets_rule.dart, lib/src/rules/avoid_unused_parameters.dart, lib/src/rules/binary_expression_operand_order_rule.dart, lib/src/rules/component_annotation_arguments_ordering.dart, lib/src/rules/double_literal_format_rule.dart, lib/src/rules/member_ordering.dart, lib/src/rules/newline_before_return.dart, lib/src/rules/no_boolean_literal_compare_rule.dart, lib/src/rules/no_empty_block.dart, lib/src/rules/no_equal_arguments.dart, lib/src/rules/no_equal_then_else.dart, lib/src/rules/no_magic_number_rule.dart, lib/src/rules/no_object_declaration.dart, lib/src/rules/potential_null_dereference.dart, lib/src/rules/prefer_conditional_expressions.dart, lib/src/rules/prefer_intl_name.dart, lib/src/rules/prefer_on_push_cd_strategy.dart, lib/src/rules/prefer_trailing_comma.dart, lib/src/rules/prefer_trailing_comma_for_collection.dart, lib/src/rules/provide_correct_intl_args.dart, lib/src/rules_factory.dart, test/rules/avoid_returning_widgets/avoid_returning_widgets_test.dart, test/rules/avoid_returning_widgets/examples/example.dart
=> feat: backport avoid returning widgets rule

.vscode/settings.json
An improvement for already closed issue #329.
=> chore: enforce LF line endings when working in Visual Studio Code

doc/rules/avoid-returning-widgets.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart, test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_test.dart, test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/examples/example.dart
We use [functional_widget](https://pub.dev/packages/functional_widget) library in our Flutter projects to avoid boilerplate code when creating simple stateless flutter widgets. 
In such case there is nothing bad in returning widgets from function because stateless widget class is being generated. So I suggest to add `ignored-annotations` option to `avoid-returning-widgets` rule to allow to use `functional_widget` library without having to always ignore rule violation.
=> feat: add `ignored-annotations` option to `avoid-returning-widgets` rule to allow using libraries like "functional_widget"

lib/src/analyzers/lint_analyzer/rules/rules_list/component_annotation_arguments_ordering/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/config_parser.dart
Removed code seems to be redundant, see https://github.com/dart-code-checker/dart-code-metrics/pull/330#discussion_r634173790
=> chore: simplify configuration parsers

CHANGELOG.md, example/example.dart, lib/config.dart, lib/metrics_analyzer.dart, lib/reporters.dart, lib/src/analyzer_plugin/analyzer_plugin.dart, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, pubspec.yaml, test/analyzers/lint_analyzer/lint_analyzer_test.dart, test/analyzers/lint_analyzer/reporters/reporters_list/html/utility_functions_test.dart, test/analyzers/lint_analyzer/reporters/reporters_list/lint_code_climate_reporter_test.dart, test/analyzers/lint_analyzer/reporters/reporters_list/lint_console_reporter_test.dart, test/analyzers/lint_analyzer/reporters/reporters_list/report_example.dart, test/analyzers/lint_analyzer/reporters/utility_selector_test.dart, test/analyzers/utils/scope_utils_test.dart, test/helpers/file_resolver.dart, test/stubs_builders.dart
[ ] Bug fix
[ ] New rule
[X] Other, please explain: migrate the package to 1.7.0 analyzer version
=> chore: migrate to 1.7.0 analyzer

analysis_options.yaml, lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering_extended/config_parser.dart
[ ] Bug fix
[ ] New rule
[x] Other, please explain: disable rule `avoid_classes_with_only_static_members`
=> build: disable rule `avoid_classes_with_only_static_members`

.github/workflows/lint_pr_title.yaml, lib/src/analyzer_plugin/analyzer_plugin.dart, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart, lib/src/analyzers/lint_analyzer/anti_patterns/models/obsolete_pattern.dart, lib/src/analyzers/lint_analyzer/anti_patterns/models/pattern.dart, lib/src/analyzers/lint_analyzer/anti_patterns/patterns_factory.dart, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, lib/src/config_builder/config_builder.dart, test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method/long_method_test.dart, test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list/long_parameter_list_test.dart, test/analyzers/lint_analyzer/anti_patterns/patterns_factory_test.dart
=> refactor: anti-pattern dependencies

CHANGELOG.md, doc/rules/prefer-extracting-callbacks.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart, test/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/examples/example.dart
[ ] Bug fix
[ ] New rule
[X] Changes an existing rule `prefer-extracting-callbacks` (#458)
`prefer-extracting-callbacks` rule doesn't trigger on the empty block functions.
–
=> feat: don't trigger prefer-extracting-callbacks on empty function blocks

CHANGELOG.md, CONTRIBUTING.md, README.md, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart, lib/src/utils/yaml_utils.dart, pubspec.yaml, test/resources/analysis_options_repo.yaml, tools/analyzer_plugin/pubspec.yaml
=> fix: unhandled exception while parsing `analysis_options.yaml`

CHANGELOG.md, doc/rules/prefer-extracting-callbacks.md, lib/src/analyzers/lint_analyzer/rules/flutter_rule_utils.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart, test/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/examples/example.dart
[ ] Bug fix
[ ] New rule
[x] Changes an existing rule
It is a pretty common situation in Flutter to have "builders". Widgets even may have multiple "builder" arguments like `titleBuilder`, `contentBuilder`, etc. We are getting violations from dart code metrics on such arguments so I think it would be ok to ignore such arguments in `prefer-extracting-callbacks` rule.
I will create a separate PR to website repository with documentation updates.  It's a little bit annoying to manually keep this repository documentation and website documentation synchronized, maybe we should start thinking about avoiding this? (we can define primary documentation source somehow, …
=> feat: ignore Flutter builder functions in "prefer-extracting-callbacks" rule

.github/workflows/no_response.yaml
=> chore: setup no-response action

.vscode/settings.json, CHANGELOG.md, lib/src/analyzers/lint_analyzer/metrics/metrics_list/maintainability_index_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/weight_of_class_metric.dart, lib/src/analyzers/lint_analyzer/metrics/models/metric.dart, lib/src/analyzers/lint_analyzer/models/summary_lint_report_record.dart, lib/src/analyzers/lint_analyzer/reporters/reporters_list/json/lint_json_reporter.dart, test/src/analyzers/lint_analyzer/reporters/reporters_list/json/lint_json_reporter_test.dart, tools/analyzer_plugin/pubspec.yaml, website/docs/cli/analyze.md
=> refactor: make violations field of summary lint report record as integer

CHANGELOG.md, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/cyclomatic_complexity/cyclomatic_complexity_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/halstead_volume/halstead_volume_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/lines_of_code_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/maintainability_index_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/maximum_nesting_level/maximum_nesting_level_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_methods_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/source_lines_of_code/source_lines_of_code_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/weight_of_class_metric.dart, lib/src/analyzers/lint_analyzer/metrics/models/file_metric.dart, lib/src/analyzers/lint_analyzer/metrics/models/metric_documentation.dart, lib/src/analyzers/lint_analyzer/reporters/utility_selector.dart, test/src/analyzers/lint_analyzer/reporters/reporters_list/report_example.dart, test/src/analyzers/lint_analyzer/reporters/utility_selector_test.dart, test/stubs_builders.dart, website/docs/metrics/overview.md
=> refactor: cleanup metric documentation

CHANGELOG.md, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart, lib/src/analyzers/lint_analyzer/anti_patterns/models/pattern_documentation.dart, website/docs/anti-patterns/overview.md, website/docs/metrics/overview.md
=> refactor: cleanup anti-patterns documentation

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_throw_in_catch_block/avoid_throw_in_catch_block_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_throw_in_catch_block/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_throw_in_catch_block/avoid_throw_in_catch_block_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_throw_in_catch_block/examples/example.dart, website/docs/rules/common/avoid-throw-in-catch-block.md, website/docs/rules/common/avoid-unnecessary-type-assertions.md, website/docs/rules/common/avoid-unnecessary-type-casts.md, website/docs/rules/overview.md
=> feat: implement avoid-throw-in-catch-block

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_missing_enum_constant_in_map/avoid_missing_enum_constant_in_map_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_missing_enum_constant_in_map/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_missing_enum_constant_in_map/avoid_missing_enum_constant_in_map_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_missing_enum_constant_in_map/examples/example.dart, website/docs/rules/common/avoid-missing-enum-constant-in-map.md, website/docs/rules/overview.md
=> feat: add avoid missing enum constant in map rule

.github/workflows/pr_author_auto_assign.yaml, CHANGELOG.md
=> chore: tune GitHub workflows

CHANGELOG.md, lib/src/analyzer_plugin/analyzer_plugin.dart, lib/src/analyzer_plugin/analyzer_plugin_utils.dart, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, pubspec.yaml, test/src/analyzer_plugin/analyzer_plugin_utils_test.dart, test/src/utils/node_utils_test.dart
=> chore: restrict `analyzer` version to `>=2.4.0 <2.9.0`

CHANGELOG.md, CONTRIBUTING.md, README.md, pubspec.yaml, tools/analyzer_plugin/pubspec.yaml, website/docs/cli/check-unused-files.md, website/docs/cli/check-unused-l10n.md
=> chore: update site

CHANGELOG.md, README.md
=> docs: add flutter favorite badge

CHANGELOG.md, analysis_options.yaml, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/maintainability_index_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/number_of_parameters_metric.dart, lib/src/analyzers/lint_analyzer/metrics/metrics_list/weight_of_class_metric.dart, lib/src/analyzers/lint_analyzer/metrics/models/file_metric.dart, lib/src/analyzers/lint_analyzer/metrics/models/metric.dart, lib/src/analyzers/lint_analyzer/reporters/reporter_factory.dart, lib/src/analyzers/lint_analyzer/reporters/reporters_list/code_climate/lint_code_climate_reporter.dart, lib/src/analyzers/lint_analyzer/reporters/reporters_list/console/lint_console_reporter.dart, lib/src/analyzers/lint_analyzer/reporters/reporters_list/github/lint_github_reporter.dart, lib/src/analyzers/lint_analyzer/reporters/reporters_list/html/lint_html_reporter.dart, lib/src/analyzers/lint_analyzer/reporters/reporters_list/json/lint_json_reporter.dart, lib/src/analyzers/unused_files_analyzer/reporters/reporter_factory.dart, lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart, lib/src/analyzers/unused_l10n_analyzer/reporters/reporter_factory.dart, lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart, lib/src/cli/commands/analyze_command.dart, lib/src/cli/commands/base_command.dart, lib/src/cli/commands/check_unused_files_command.dart, lib/src/cli/commands/check_unused_l10n_command.dart, test/src/analyzers/lint_analyzer/reporters/reporters_list/report_example.dart
[ ] Bug fix
[ ] New rule
[X] Other, please explain: active some rules
https://github.com/dart-lang/language/blob/master/resources/type-system/strict-raw-types.md
https://github.com/dart-lang/language/blob/master/resources/type-system/strict-inference.md
=> chore: activate language strict rules

README.md
[ ] Bug fix
[ ] New rule
Add content section in readme
=> feat: add content section in readme file

CHANGELOG.md, pubspec.yaml
=> chore: support analyzer 3.0.x

CHANGELOG.md, analysis_options.yaml, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/avoid_global_state_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/avoid_global_state_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/examples/example.dart, website/docs/rules/common/avoid-global-state.md
[ ] Bug fix
[X] New rule
https://github.com/dart-code-checker/dart-code-metrics/issues/536
=> feat: add static code diagnostics `avoid-global-state`.

CHANGELOG.md, test/src/cli/commands/analyze_command_test.dart, test/src/cli/commands/check_unused_files_command_test.dart, test/src/cli/commands/check_unused_l10n_command_test.dart, website/docs/rules/common/avoid-global-state.md, website/docs/rules/overview.md
[ ] Bug fix
[ ] New rule
[x] Other, please explain: replace regular expression by current path in command usage tests
=> fix: stabilized command usage tests

CHANGELOG.md, lib/src/analyzers/unused_l10n_analyzer/unused_l10n_visitor.dart, test/resources/unused_l10n_analyzer/test_i18n.dart, test/resources/unused_l10n_analyzer/unused_l10n_analyzer_example.dart, test/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer_test.dart
Support l10n extensions
[ ] Bug fix
[ ] New rule
- I didn't include tests because:
- Current tests are not working on my local.
- Documentation is not clear about how to use `check-unused-l10n`. https://dartcodemetrics.dev/docs/cli/check-unused-l10n
The -p param would be used to find files with that pattern too, is not just for Class names.
- The changes I made were on `UnusedL10nVisitor` class, now we support unused code called from extensions, the only requirements to find unused Strings on extension are:
-  The file name where the `Localization` is implemented should contain the name of the getter for the extension. Eg:
```dart …
```
=> feat: Support l10n extensions

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/prefer_extracting_callbacks_rule_test.dart
This PR fixes `prefer-extracting-callbacks` for nested widgets.
=> fix: prefer-extracting-callbacks in nested widgets

CHANGELOG.md, lib/src/analyzers/unused_l10n_analyzer/unused_l10n_visitor.dart, test/resources/unused_l10n_analyzer/test_i18n.dart, test/resources/unused_l10n_analyzer/unused_l10n_analyzer_example.dart, test/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer_test.dart
=> fix: correctly handle method invocations on getters

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/avoid_global_state_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/examples/example.dart
[X] Bug fix
[ ] New rule
https://github.com/dart-code-checker/dart-code-metrics/issues/643
Added support static fields.
=> fix: `avoid-global-state` to support static fields

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/visitor.dart, pubspec.yaml, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/avoid_global_state_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/examples/example.dart
=> chore: restrict `analyzer` version to `>=2.4.0 <3.2.0`.

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/avoid_global_state_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_global_state/examples/example.dart
[X] Bug fix
[ ] New rule
ignore private variables in `avoid-global-state` rule
=> fix: ignore private variables in `avoid-global-state` rule

CHANGELOG.md, lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart, test/resources/unused_l10n_analyzer/test_i18n.dart
[ ] Bug fix
[ ] New rule
[X] Other, please explain: fix private members triggering for `check-unused-l10n`
=> feat: ignore private members for check-unused-l10n command

CHANGELOG.md, lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart, test/resources/unused_l10n_analyzer/base_localization.dart, test/resources/unused_l10n_analyzer/test_i18n.dart, test/resources/unused_l10n_analyzer/unused_l10n_analyzer_example.dart, test/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer_test.dart
=> fix: make `check-unused-l10n` also cover supertype member calls

CHANGELOG.md, lib/src/cli/cli_runner.dart, lib/src/cli/models/flag_names.dart, lib/src/version.dart, test/src/cli/cli_runner_test.dart, test/src/cli/commands/analyze_command_test.dart, test/src/cli/commands/base_command_test.dart, test/src/cli/commands/check_unused_code_command_test.dart, test/src/cli/commands/check_unused_files_command_test.dart, test/src/cli/commands/check_unused_l10n_command_test.dart
[ ] Bug fix
[ ] New rule
[X] Add a CLI option
=> feat: add version flag to print package version

website/docs/getting-started/configuration.md
Use proper name for number-of-parameters metric in Getting started/Configuration page
=> docs: change name of metric number-of-arguments to number-of-parameters

CHANGELOG.md, lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart, lib/src/utils/node_utils.dart
[ ] Bug fix
[ ] New rule
[X] Other, please explain:
Command check-unused-files now triggered on some system files:
lib/generated_plugin_registrant.dart
[test/flutter_test_config.dart](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html)
that files need for correct works but never imported in project.
=> fix: `check-unused-files` now ignored some system files

CHANGELOG.md, lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart, lib/src/analyzers/unused_code_analyzer/unused_code_config.dart, lib/src/cli/cli_runner.dart, lib/src/cli/commands/check_unused_code_command.dart, lib/src/cli/models/flag_names.dart, lib/src/config_builder/config_builder.dart, test/src/analyzers/unused_code_analyzer/unused_code_analyzer_test.dart, test/src/cli/commands/check_unused_code_command_test.dart, website/docs/cli/check-unused-code.md
[ ] Bug fix
[ ] New rule
[X] Other, please explain: monorepos support for `check-unused-code command`
=> feat: add experimental monorepo support for check-unused-code

.vscode/settings.json, CHANGELOG.md, CONTRIBUTING.md, README.md, lib/src/cli/cli_runner.dart, lib/src/version.dart, pubspec.yaml, tools/analyzer_plugin/pubspec.yaml, website/docs/cli/analyze.md, website/docs/getting-started/installation.md
=> fix: restore `analyze` command as default command

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/avoid_dynamic_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/avoid_dynamic_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/examples/example.dart, website/docs/rules/common/avoid-dynamic.md, website/docs/rules/overview.md
=> feat: add avoid-dynamic rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_async_await/prefer_async_await_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_async_await/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_async_await/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_async_await/prefer_async_await_rule_test.dart, website/docs/rules/common/prefer-async-await.md, website/docs/rules/overview.md
=> feat: add prefer-async-await rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/examples/example.dart
[ ] Bug fix
[ ] New rule
[X] Changes an existing rule
=> feat: improve avoid-returning-widgets builder functions handling

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/avoid_border_all_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/prefer_const_border_radius_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/avoid_border_all_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/prefer_const_border_radius_rule_test.dart, website/docs/rules/flutter/avoid-border-all.md, website/docs/rules/flutter/prefer-const-border-radius.md, website/docs/rules/overview.md
[ ] Bug fix
[X] New rule
Border.all({
Color color = const Color(0xFF000000),
double width = 1.0,
BorderStyle style = BorderStyle.solid,
}) // LINT
=> feat: add static code diagnostics `avoid-border-all`.

CHANGELOG.md, analysis_options.yaml, lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart
=> fix: correctly handle excluded files for check-unused-code

CHANGELOG.md, analysis_options.yaml, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/avoid_collection_methods_with_unrelated_types_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_single_widget_per_file/visitor.dart, pubspec.yaml, website/docs/cli/check-unused-files.md
=> chore: bump analyzer

website/docs/rules/common/no-equal-then-else.md
[ ] Bug fix
[ ] New rule
I changed "value1" and "value2" to "firstValue" and "secondValue" in the docs for no-equal-then-else.
This change may seen small, but I've been stuck reading the two same code blocks for around 5 minutes,
trying to figure out whether the docs were wrong or I was having an aneurysm. The numbers 1 and 2 are too similar
to be easily distinguisable, but "first" and "second" have different lengths, so it should be
easier for another devs to distiguish between the two variables
=> docs: Improve readability of no-equal-then-else description

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/prefer_immediate_return_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/prefer_immediate_return_rule_test.dart, website/docs/rules/common/prefer-immediate-return.md, website/docs/rules/overview.md
[ ] Bug fix
[x] New rule
https://github.com/dart-code-checker/dart-code-metrics/issues/474
The fixer implemented is something like "semi-automatic" fixer, it does only half of the work required :) It replaces only expression in the problematic return statement and code contains unused variable after that.
For example,
```dart
int calculateSum(int a, int b) {
final sum = a + b; 
return sum;
}
```
will be fixed as 
```dart
int calculateSum(int a, int b) {
final sum = a + b; 
return a + b;
}
```
and `sum` variable should be manually removed. I think that this shoud be acceptable - it's not a huge amount of work to manually remove …
=> feat: add prefer-immediate-return rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/no_magic_number_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/examples/exceptions_example.dart
=> fix: support index expressions for no-magic-number rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_null_assertion/avoid_non_null_assertion_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_null_assertion/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_null_assertion/examples/example.dart
=> fix: add check for supertypes

website/docs/rules/flutter/avoid-border-all.md
Fix `Border.all` constructor arguments’ syntax.
=> docs(avoid-border-all): fix `Border.all` constructor syntax

CHANGELOG.md, lib/src/analyzers/lint_analyzer/utils/report_utils.dart
Hi thanks for this flutter-favorite package! It is crashing because of `.max` on empty array. So here is the fix.
Closes #804
=> fix: dart-code-metrics crash saying `Bad state: No element` when running command

CHANGELOG.md, lib/src/config_builder/models/analysis_options.dart, test/src/config_builder/models/analysis_options_test.dart
=> fix: correctly handle disabling rules with false

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/prefer_immediate_return_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/visitor.dart, lib/src/utils/node_utils.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_immediate_return/prefer_immediate_return_rule_test.dart
[ ] Bug fix
[ ] New rule
[x] Changes an existing rule
`prefer-immediate-return` will remove variable declaration as well, if this is a single declaration (e.g. it will remove `final x = 1` but not `final a = 2, x = 1`).
It will solve the most common use case, when there's a single variable declaration and immediate return.
=> feat: remove declaration in prefer-immediate-return

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_ascii_symbols/avoid_non_ascii_symbols_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_ascii_symbols/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_ascii_symbols/avoid_non_ascii_symbols_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_non_ascii_symbols/examples/example.dart, website/docs/rules/common/avoid-non-ascii-symbols.md, website/docs/rules/overview.md
=> feat: avoid-non-ascii-symbols rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/examples/example_documentation.dart
[X] Bug fix
[ ] New rule
https://github.com/dart-code-checker/dart-code-metrics/issues/812
=> fix: `format-comment` is listing the macros from dart doc.

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/examples/example.dart
[X] Bug fix
[ ] New rule
https://github.com/dart-code-checker/dart-code-metrics/issues/837
=> fix: avoid-border-all is triggered even when it is not a const

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/prefer_moving_to_variable_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/arguments_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/arguments_with_object_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/scope_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/prefer_moving_to_variable_rule_test.dart
=> fix: remove duplicated highlights and ignore void function calls

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/examples/incorrect_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/prefer_trailing_comma_rule_test.dart
=> fix: temporary remove enums support

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_test.dart, website/docs/rules/common/format-comment.md, website/docs/rules/overview.md
[ ] Bug fix
[ ] New rule
[x] Changes an existing rule
Should close https://github.com/dart-code-checker/dart-code-metrics/issues/826
I added the option `ignored-patterns` (a list of strings that will be used as regexes) to the rule `format-comment` to be able to ignore some kind of comments.
Am I correctly getting the `ignored-patterns` option from the `config` ? I didn't find how to test it myself (e2e test) and make sure my code is actually working.
Also, do I have to apply any change to your web site? If yes, how?
=> feat: Add the option `ignored-patterns` to the rule `format-comment`

.vscode/settings.json, CHANGELOG.md, dart_dependency_validator.yaml, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart, lib/src/analyzers/unused_files_analyzer/unused_files_analyzer.dart, lib/src/analyzers/unused_l10n_analyzer/unused_l10n_analyzer.dart, lib/src/config_builder/models/analysis_options.dart, pubspec.yaml, test/resources/analysis_options_with_import.yaml, test/resources/test_lints/lib/analysis_options.1.0.0.yaml, test/resources/test_lints/lib/analysis_options.yaml, test/resources/test_lints/pubspec.yaml, test/src/config_builder/models/analysis_options_test.dart
=> fix: resolve package with imported analysis options

CHANGELOG.md, lib/src/utils/file_utils.dart, test/src/utils/analyzer_utils_test.dart
=> fix: normalize file paths after extraction from analyzed folder

CHANGELOG.md, lib/src/analyzers/lint_analyzer/reporters/reporters_list/checkstyle/lint_checkstyle_reporter.dart, test/src/analyzers/lint_analyzer/reporters/reporters_list/checkstyle/lint_checkstyle_reporter_test.dart
[ ] Bug fix
[ ] New rule
Potentially close #842
=> feat: improve checkstyle report, added metrics entries

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/examples/example.dart
=> fix: correctly handle `-` symbol

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_expanded_as_spacer/avoid_expanded_as_spacer_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_expanded_as_spacer/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_expanded_as_spacer/avoid_expanded_as_spacer_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_expanded_as_spacer/examples/example.dart, website/docs/rules/common/avoid-banned-imports.md, website/docs/rules/flutter/avoid-use-expanded-as-spacer.md, website/docs/rules/overview.md
…ps://dartcodemetrics.dev/docs/rules/flutter/avoid-use-expanded-as-spacer).
[ ] Bug fix
[X] New rule
https://github.com/dart-code-checker/dart-code-metrics/issues/898
=> feat: add static code diagnostic `avoid-use-expanded-as-spacer`

.github/ISSUE_TEMPLATE/new-rule-proposal.md, .github/PULL_REQUEST_TEMPLATE.md
=> fix: Checkbox in ISSUE_TEMPLATE

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_top_level_members_in_tests/avoid_top_level_members_in_tests_rule.dart
Issues: https://github.com/dart-code-checker/dart-code-metrics/issues/944
I added all the folders (`'*'`) so that only the test folder is taken into account.
I tried to do a test to see if the file was being ignored, but I have the impression that the exclusion is done in another part of the code.
As it stands, this is the only rule that doesn't take excludes in parameters.
Is this normal?
We could add the excludes of the config or replace the existing excludes.
=> fix: avoid-top-level-members-in-tests

lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/avoid_border_all_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_border_all/examples/example_with_final_variables.dart
I've made the following code not trigger warnings:
```dart
final aLocalColor = Colors.red;
Border.all(color: aLocalColor);
```
#973.
I would like to know If there's any way that we could refactor this rule such that we didn't have to cover each and every case separately.
=> fix: make avoid-border-all not report errors on final variables

lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/avoid_passing_async_when_sync_expected.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/avoid_passing_async_when_sync_expected.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/examples/example.dart, website/docs/rules/common/avoid-passing-async-when-sync-expected.mdx, website/docs/rules/index.mdx
I've added a new rule, `avoid-passing-async-when-sync-expected`, which warns the user about async functions being passed as argument where a sync function was expected. This is helpful because the function won't be awaited as the user may expect.
#886
Please, feel free to give advice on any other way to write the same rule in a more elegant way. I'm not familiar with the analyzer API xD.
=> feat: avoid passing async when sync expected

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/check_for_equals_in_render_object_setters/check_for_equals_in_render_object_setters_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/check_for_equals_in_render_object_setters/visitor.dart, lib/src/utils/flutter_types_utils.dart, test/src/analyzers/lint_analyzer/rules/rules_list/check_for_equals_in_render_object_setters/check_for_equals_in_render_object_setters_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/check_for_equals_in_render_object_setters/examples/example.dart, website/docs/rules/flutter/check-for-equals-in-render-object-setters.mdx, website/docs/rules/index.mdx
=> feat: add static code diagnostic check-for-equals-in-render-object-setters

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_wrapping_in_padding/avoid_wrapping_in_padding_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_wrapping_in_padding/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_wrapping_in_padding/avoid_wrapping_in_padding_rule_test.dart
=> fix: make avoid-wrapping-in-padding trigger only on Container widget

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/avoid_redundant_async_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/examples/example.dart
=> fix: make avoid-redundant-async correctly handle nullable return values

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/examples/example.dart
=> fix: make avoid-redundant-async handle yield

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/missing_test_assertion_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/examples/custom_methods_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/missing_test_assertion_test.dart, website/docs/rules/common/missing-test-assertion.mdx
Completes issue #1019, PR #1023 
This PR aims at completing issue #1019 and PR #1023 about the new missing_test_assertion rule, by adding the possibility to enter additional test methods names to be checked in addition to the default `test` and `testWidgets` methods.
This new config might be useful when using dedicated test methods that potentially come from other packages, or just test wrappers written by the developers. E.g. we could create a base `companyXTest()` method that acts as a wrapper around test/testWidgets and sets some basic configuration for our company tests.  
As a side note, I also changed the severity from "style" to "warning" in the doc, seems more appropriate.
Config name, I can change it if "include-methods" is not clear enough.
=> feat: add 'include-methods' config to 'missing-test-assertion' rule

.github/workflows/package_analyze.yaml, CHANGELOG.md, lib/cli_runner.dart, website/docs/cli/index.md
=> feat: export cli runner and add documentation for use-case

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/models/member_group.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/examples/flutter_widget_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/member_ordering/member_ordering_rule_test.dart, website/docs/rules/common/member-ordering.mdx
=> feat: support dynamic method name for member-ordering

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_iterable_of/visitor.dart, pubspec.yaml, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_iterable_of/examples/queue_list_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_iterable_of/prefer_iterable_of_rule_test.dart
- https://github.com/dart-code-checker/dart-code-metrics/issues/1046
I check if the type contain a `of` constructor.
No
=> fix: check `of` constructor exist for `prefer-iterable-of`

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/avoid_banned_imports_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/prefer_trailing_comma_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/tag_name/tag_name_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/avoid_banned_imports_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_iterable_of/prefer_iterable_of_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_trailing_comma/prefer_trailing_comma_rule_test.dart, website/docs/rules/common/avoid-banned-imports.mdx, website/docs/rules/common/ban-name.mdx, website/docs/rules/common/prefer-trailing-comma.mdx, website/docs/rules/index.mdx
=> feat: change severity for avoid-banned-imports, prefer-trailing-comma, ban-name rules

pubspec.yaml
=> chore: specify platform support in the pubspec

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/examples/example.dart
=> fix: ignore override methods for avoid-redundant-async

CHANGELOG.md, lib/src/analyzers/lint_analyzer/lint_analysis_options_validator.dart, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
=> fix: correctly available check rule names

lib/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/missing_test_assertion/examples/correct_example.dart, website/docs/rules/common/missing-test-assertion.mdx
Add `fail` method as a valid test assertion for missing_test_assertion as it is a valid way to make an assertion in a test.
=> fix: add fail assertion as a valid method to missing_test_assertion rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/arguments_ordering_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/arguments_ordering_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/examples/class_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/examples/function_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/examples/mixed_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/examples/widget_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/arguments_ordering/examples/widget_example_child_last.dart, website/docs/rules/common/arguments-ordering.mdx, website/docs/rules/index.mdx
Enforces named argument order in function and constructor invocations to be the same as corresponding named parameter declaration order.
The rule can be used together with [sort_child_properties_last](https://dart-lang.github.io/linter/lints/sort_child_properties_last.html) rule by setting `child-last: true` in rule configuration.
```yaml
dart_code_metrics:
...
rules:
...
- arguments-ordering:
child-last: true
```
**❌ Bad:**
```dart
Person buildPerson({ String name, String surname, String age });
// LINT
final person = buildPerson(age: 42, surname: 'The Pooh', name: 'Winnie');
```
**✅ Good:**
```dart
Person buildPerson({ String name, String surname, String age });
// LINT
final person = buildPerson(name: 'Winnie', surname: 'The Pooh', age: 42);
```
=> feat: add static code diagnostic arguments-ordering

lib/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/ban_name/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/ban_name/examples/classes.dart, test/src/analyzers/lint_analyzer/rules/rules_list/ban_name/examples/example.dart, website/docs/rules/common/ban-name.mdx
This PR extends the ban-name rule abilities to recursive search in method call chains. (ex: `DateTime.now` or `StrangeClass.someField.subField` etc.)
Ban-name rule's visitor will have a breadcrumb now and will compare breadcrumb node names with the rule ident.
Resolves the #927 
> **IMPORTANT:**
> Tests passes, CLI works as expected. But the IDE does not highlight method call chains. I'm trying to figure out what's wrong
>
> **UPD:**
> **Progress is [here](https://github.com/dart-lang/sdk/issues/50209)**
=> feat: add method call chains support on ban-name ident

CHANGELOG.md, lib/presets/dart_all.yaml
=> fix: update presets

CHANGELOG.md, CONTRIBUTING.md
We have sort of [checklist](https://github.com/dart-code-checker/dart-code-metrics/blob/master/CONTRIBUTING.md#creating-new-lint-rule) describing things to be done to implementing new rule. I found that it is missing some information and decided to update it.
=> docs: improve rule checklist for contributors

website/docs/getting-started/configuration.md
I added rules in the example to show that you can disable a rule or override a rule.
No
=> docs: Add better example for presets

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/ban_name/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule_test.dart
=> fix: remove recursive traversal for ban-name

CHANGELOG.md, lib/presets/flutter_all.yaml, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_using_list_view/prefer_using_list_view_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_using_list_view/visitor.dart, lib/src/utils/flutter_types_utils.dart, test/src/analyzers/lint_analyzer/rules/rules_factory_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_using_list_view/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_using_list_view/prefer_using_list_view_rule_test.dart, website/docs/rules/flutter/prefer-using-list-view.mdx, website/docs/rules/index.mdx
- #400
Add static code diagnostic `prefer-using-list-view`
I check `SingleChildScrollView` with `child` `Column` with only `children` parameter.
Not to my knowledge.
=> feat: add static code diagnostic `prefer-using-list-view`

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_double_slash_imports/avoid_double_slash_imports_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_double_slash_imports/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_double_slash_imports/avoid_double_slash_imports_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_double_slash_imports/examples/example.dart, website/docs/rules/common/avoid-double-slash-imports.mdx, website/docs/rules/index.mdx
See: https://github.com/dart-lang/sdk/issues/36337
=> feat: add avoid-double-slash-imports rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/prefer_conditional_expressions_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/prefer_conditional_expressions_rule_test.dart
Second part of #1094 improving the existing rule to discard boolean literals.
=> feat: support boolean literals removal for prefer-conditional-expressions auto-fix

CHANGELOG.md, lib/src/analyzers/unused_code_analyzer/models/file_elements_usage.dart, lib/src/analyzers/unused_code_analyzer/unused_code_analyzer.dart, lib/src/analyzers/unused_code_analyzer/used_code_visitor.dart, test/resources/unused_code_analyzer/conditional_prefixed_file.dart, test/resources/unused_code_analyzer/unconditional_prefixed_file.dart, test/resources/unused_code_analyzer/unused_code_example.dart, test/src/analyzers/unused_code_analyzer/unused_code_analyzer_test.dart
=> fix: correctly support conditional imports for check-unused-code

analysis_options.yaml
Reference: https://github.com/dart-lang/sdk/issues/50751
=> chore: remove strong-mode from analysis_options since it is no longer supported

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_rule_test.dart, website/docs/rules/common/format-comment.mdx
=> feat: support ignoring regular comments for format-comment

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/generics_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/prefer_moving_to_variable_rule_test.dart
=> fix: support function expression invocations for prefer-moving-to-variable

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/avoid_collection_methods_with_unrelated_types_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/avoid_collection_methods_with_unrelated_types_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_collection_methods_with_unrelated_types/examples/dynamic_example.dart, website/docs/rules/common/avoid-collection-methods-with-unrelated-types.mdx
=> feat: add strict config option to avoid-collection-methods-with-unrelated-types

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/prefer_commenting_analyzer_ignores_rule_test.dart
=> fix: ignore doc comments for prefer-commenting-analyzer-ignores

CHANGELOG.md, analysis_options.yaml, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/list_all_equatable_fields/list_all_equatable_fields_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/list_all_equatable_fields/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/list_all_equatable_fields/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/list_all_equatable_fields/list_all_equatable_fields_rule_test.dart, website/docs/rules/common/list-all-equatable-fields.mdx, website/docs/rules/index.mdx
Not adding docs for now, waiting for the rule behaviour to be approved.
=> feat: add list-all-equatable-fields rule

CHANGELOG.md, lib/src/utils/flutter_types_utils.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/examples/provider_example.dart
=> fix: ignore Providers for avoid-returning-widgets

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/prefer_conditional_expressions_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_static_class/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_static_class/prefer_static_class_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/examples/nested_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_conditional_expressions/prefer_conditional_expressions_rule_test.dart, website/docs/rules/common/prefer-conditional-expressions.mdx, website/docs/rules/index.mdx
=> feat: support ignoring nesting for prefer-conditional-expressions

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/avoid_redundant_async_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/avoid_redundant_async_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/examples/example.dart
=> fix: correctly handle FunctionExpressions for avoid-redundant-async

CHANGELOG.md, lib/src/analyzers/lint_analyzer/lint_analysis_options_validator.dart, lib/src/analyzers/lint_analyzer/rules/models/rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/avoid_banned_imports_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/ban_name/ban_name_rule.dart
=> feat: show warning for rules without config that require config to work

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_redundant_async/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/visitor.dart, lib/src/utils/node_utils.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/avoid_unused_parameters_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_unused_parameters/examples/tear_off_example.dart
=> feat: ignore tear-off methods for avoid-unused-parameters

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/use_setstate_synchronously_rule_test.dart, website/docs/rules/flutter/use-setstate-synchronously.mdx
Fixes mountedness invalidation in this case:
```dart
if (mounted) { // or 'while'
await fetch();
}
setState(() {}); // LINT
```
=> fix: use-setstate-synchronously edge cases

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/models/comment_info.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/models/comment_type.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/examples/example_without_issue.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/examples/multiline_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/format_comment_rule_test.dart
=> fix: handle multiline comments

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/helpers.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/extras_try_switch.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/known_errors.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/use_setstate_synchronously_rule_test.dart, website/docs/rules/flutter/use-setstate-synchronously.mdx
- Handle `try` and `switch` branches, closes #1133
- Handle `break` and `continue` in control flow statements
=> fix: additional cases for `use-setstate-synchronously`

.github/workflows/package_analyze.yaml
=> chore: add permissions for tests reporting

lib/src/analyzers/lint_analyzer/rules/rules_list/list_all_equatable_fields/list_all_equatable_fields_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/list_all_equatable_fields/list_all_equatable_fields_rule_test.dart
Initially `list-all-equatable-fields` was introduced as `FlutterRule` but properly documented as Common. Now when clicking on `Missing declared class fields: XYZ (Documentation)` inspection warning, the user ends up in wrong doc path:
=> fix: list-all-equatable-fields should be typed common

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_late_keyword/avoid_late_keyword_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_late_keyword/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_late_keyword/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_late_keyword/avoid_late_keyword_rule_test.dart, website/docs/rules/common/avoid-late-keyword.mdx, website/docs/rules/index.mdx, website/docs/rules/intl/prefer-provide-intl-description.mdx
=> feat: add allow-initialized option to avoid-late-keyword

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/assignment_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/prefer_moving_to_variable_rule_test.dart
=> fix: ignore method invocations in a variable declaration for prefer-moving-to-variable

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/no_magic_number_rule.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/examples/enum_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/no_magic_number_rule_test.dart
Ignoring numbers in enum
<details>
<summary>Example</summary>
```dart
enum ExitCode {
/// The successful exit.
success(0),
/// The command was used incorrectly.
usage(64),
/// An internal software error has been detected.
software(70),
/// Something was found in an unconfigured or misconfigured state.
config(78);
final int code;
const ExitCode(this.code);
}
```
</details>
=> fix: ignore enum constant arguments for no-magic-number

CHANGELOG.md, lib/src/analyzers/unnecessary_nullable_analyzer/invocations_visitor.dart, lib/src/analyzers/unnecessary_nullable_analyzer/models/invocations_usage.dart, test/resources/unnecessary_nullable_analyzer/nullable_method_parameters.dart, test/resources/unnecessary_nullable_analyzer/nullable_widget_key_parameters.dart, test/resources/unnecessary_nullable_analyzer/unnecessary_nullable_example.dart
=> fix: support tear-off methods for check-unnecessary-nullable

CHANGELOG.md, lib/src/analyzers/lint_analyzer/lint_analyzer.dart, lib/src/utils/suppression.dart, test/resources/suppression_all_example.dart, test/src/analyzers/lint_analyzer/models/suppression_test.dart
=> feat: support type=lint suppression

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart
=> fix: correctly handle empty comment sentence for format-comment

CHANGELOG.md, lib/lint_analyzer.dart, lib/unnecessary_nullable_analyzer.dart, lib/unused_code_analyzer.dart, lib/unused_files_analyzer.dart, lib/unused_l10n_analyzer.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_empty_block/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_empty_block/no_empty_block_rule_test.dart
=> fix: export missing parts of public API

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/helpers.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/context_mounted.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/use_setstate_synchronously_rule_test.dart
=> feat: support context.mounted for use-setstate-synchronously

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/format_comment/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/format_comment/examples/example_documentation.dart
Add dartdoc tags support for `format-comment`.
=> fix: correctly support dartdoc tags for format-comment

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/use_setstate_synchronously_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/assert_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/use_setstate_synchronously_rule_test.dart
=> fix: support assert(mounted) for use-setstate-synchronously

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/assignment_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/provider_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/examples/while_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/prefer_moving_to_variable_rule_test.dart
Fixes newly reported false positives for `prefer-moving-to-variable`.
=> fix: fix moving to variable false positives

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/config_parser.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/no_equal_arguments_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/no_equal_arguments_rule_test.dart
Adds new config option `ignored-arguments` to `no-equal-arguments` rule.
=> feat: add new config option

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/examples/example.dart
Add missing check for `didChangeDependencies`.
=> fix: check didChangeDependencies for avoid-unnecessary-setstate

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/avoid_passing_async_when_sync_expected_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/avoid_passing_async_when_sync_expected_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_passing_async_when_sync_expected/examples/example.dart
Properly handle `dynamic` type.
=> fix: correctly handle dynamic type for avoid-passing-async-when-sync-expected

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart, lib/src/utils/node_utils.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/examples/provider_example.dart, test/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/no_equal_arguments_rule_test.dart
Fix implicit type parameters for `no-equal-arguments`.
=> fix: correctly handle implicit type parameters for no-equal-arguments

CHANGELOG.md, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart
=> fix: change anti-patterns default severity to warning

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_factory.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_substring/avoid_substring_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_substring/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_substring/avoid_substring_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_substring/examples/example.dart
Issue: #1201 
- \[x] Read the [contributing guidelines](https://github.com/dart-code-checker/dart-code-metrics/blob/master/CONTRIBUTING.md).
- \[x] Followed lint naming conventions
- \[x] Tests pass locally
- \[x] Updated the changelog
- \[ ] Added the docs to this PR
```markdown
Replace s.substring(100,200) to s.characters.getRange(100,200).
As we know, using String.substring method will cause problems if you are having emojis in the string. 
There are many articles in the web, such as [substring does not support UTF-16](https://github.com/dart-lang/sdk/issues/35798).
```
```dart
s.characters.getRange(14, 15); 
```
```dart
s.substring(14, 15); 
```
=> feat: add avoid-substring rule

CHANGELOG.md, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart, lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_ignoring_return_values/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/check_for_equals_in_render_object_setters/visitor.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_moving_to_variable/visitor.dart, pubspec.yaml, test/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method/long_method_test.dart, test/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list/long_parameter_list_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/avoid_dynamic_rule_test.dart, test/src/analyzers/lint_analyzer/rules/rules_list/avoid_dynamic/examples/example.dart
=> fix: handle dynamics in map literals for avoid-dynamic

CHANGELOG.md, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/use_setstate_synchronously_rule.dart, lib/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/visitor.dart, test/src/analyzers/lint_analyzer/rules/rules_list/use_setstate_synchronously/examples/example.dart
Fix false-positives for `use-setstate-synchronously`.
=> fix: visit only widgets for use-setstate-synchronously
